### ISSUE TITLE
Setup Remix Auth

### ISSUE THREAD

**Issue by Olie440** [Olie440/react-2024-practice#2]
### Summary
I want to enable authentication for my app so that i can have user specific state (also its good pratice). I have decided to use remix auth since its is well integrated with remix. The user will be retreved from the session in the root loader and then passed down to the root route which will hydrate a jotai atom with it so it is accessible anywhere in the react tree. 

### Dependencies
- #7 

### Tasks
- [x] Create a cookie session in Remix
- [x] Setup Remix Auth
- [x] Get the user the the root loader and pass it down to the root route then into jotai

### Testing
This is a setup ticket so it will be tested with unit tests alone, tickets [#4: Create email and password login form](https://github.com/Olie440/react-2024-practice/issues/4) and [#5: Create email and password register form](https://github.com/Olie440/react-2024-practice/issues/5) will test the functionality.
