### ISSUE TITLE
Create email and password register form

### ISSUE THREAD

**Issue by Olie440** [Olie440/react-2024-practice#5]
### Summary
Create a register form so that users can register accounts using their email and a password. OTP and Passkeys will be covered in later tickets. I will use the [OWASP guidelines](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls) for password strength. The backend will return a generic message regardless of if the account already exists or not as per [OWASP guidelines](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#account-creation) until/if CAPTCHA is implemented.

### Dependencies
- https://github.com/Olie440/react-2024-practice/issues/2

### Tasks
- [x] Create a /register Route
- [ ] Create a form with the following fields:
  - [x] Email
  - [x] Password
  - [ ] Password strength bar
  - [x] Confirm Password
  - [ ] Slot for server error message
  - [x] Submit button
- [ ] Implement frontend validation:
   - [ ] Email invalid format
   - [ ] Password too short
   - [ ] Password too long
   - [ ] Password not strong enough
   - [ ] Passwords don't match
 - [ ] Create a route action that:
   - [ ] Checks the input against the front-end validation schema incase the front end validaition has been bypassed
   - [ ] Hashes the password
   - [ ] Tries to insert the user into the users table
   - [ ] Sends a activation link if the request is successful (Note: In the real world this would be a message to another service to protect against time based enumeration but for this small project it doesn't matter that much) 
   - [ ] Redirects to the success page if user is created successfully or if the user already exists
   - [ ] Throws a "please try again" error message for genuine errors
   
### A/C
- [ ] I am able to create an account using my email and password
- [ ] WhenI register an account I am sent a activation link via email
- [ ] If I try and register an account that already exists no email gets sent
- [ ] If I try and use a password that is too weak I am given a frontend validation warning
- [ ] If I try and enter an invalid email I am given a frontend validation warning
- [ ] If not my repeated passsword does not match I am given a validation warning
