### ISSUE TITLE
Setup Database

### ISSUE THREAD

**Issue by Olie440** [Olie440/react-2024-practice#7]
### Summary
I will need a database to store my auth credentials in. It should be both secure and reproducible. I will use an orm to both access and deploy the database, this will require a bit of research. 

### Dependencies
None

### Tasks
- [x] Find and install an ORM
- [x] Figure out how I will store dev credentials (I suspect it will be in the commited .env file)
- [x] Research best pratices for storing passwords
- [x] Research best pratices for database user permissions
- [x] Setup a deployment schema
- [x] Setup a users table with email and hash + salted password
- [x] Connect the orm to the database
- [x] Research best pratices around testing database logic in node

### A/C
- [x] I am able run a script to setup a fresh copy of the database
- [x] I am able run a script to cleardown and setup a clean version of the database
- [x] I am able to import the orm and query and update the database from a function
- [x]  I am able to unit test functions that call the db
